"""Modyfikacja tabeli Regular_Event.

Revision ID: 0f2978dc54e3
Revises: c7a20dd4915e
Create Date: 2022-05-10 20:36:24.370703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2978dc54e3'
down_revision = 'c7a20dd4915e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Regular_Events', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('Regular_Events', sa.Column('stop_date', sa.DateTime(), nullable=False))
    op.add_column('Regular_Events', sa.Column('period', sa.Interval(), nullable=False))
    op.drop_column('Regular_Events', 'monthly')
    op.drop_column('Regular_Events', 'weekly')
    op.drop_column('Regular_Events', 'yearly')
    op.drop_column('Regular_Events', 'daily')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Regular_Events', sa.Column('daily', sa.BOOLEAN(), nullable=False))
    op.add_column('Regular_Events', sa.Column('yearly', sa.BOOLEAN(), nullable=False))
    op.add_column('Regular_Events', sa.Column('weekly', sa.BOOLEAN(), nullable=False))
    op.add_column('Regular_Events', sa.Column('monthly', sa.BOOLEAN(), nullable=False))
    op.drop_column('Regular_Events', 'period')
    op.drop_column('Regular_Events', 'stop_date')
    op.drop_column('Regular_Events', 'start_date')
    # ### end Alembic commands ###
