"""empty message

Revision ID: c7a20dd4915e
Revises: 
Create Date: 2022-05-10 19:00:52.576176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a20dd4915e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('stop_date', sa.DateTime(), nullable=False),
    sa.Column('types', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Regular_Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily', sa.Boolean(), nullable=False),
    sa.Column('weekly', sa.Boolean(), nullable=False),
    sa.Column('monthly', sa.Boolean(), nullable=False),
    sa.Column('yearly', sa.Boolean(), nullable=False),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users_Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Boolean(), nullable=False),
    sa.Column('finish', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('aprove', sa.Boolean(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['Events.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rem_before', sa.Interval(), nullable=False),
    sa.Column('id_users_events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_users_events'], ['Users_Events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=50), nullable=False),
    sa.Column('id_users_events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_users_events'], ['Users_Events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tags')
    op.drop_table('Reminders')
    op.drop_table('Users_Events')
    op.drop_table('Regular_Events')
    op.drop_table('Users')
    op.drop_table('Events')
    # ### end Alembic commands ###
