"""Dodanie tabeli Events, Users_Events, Tags, Reminders.

Revision ID: e91d6bb9c92e
Revises: c28d0a7d58c1
Create Date: 2022-04-13 19:39:12.735913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91d6bb9c92e'
down_revision = 'c28d0a7d58c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('stop_date', sa.DateTime(), nullable=False),
    sa.Column('types', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rem_before', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users_Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Boolean(), nullable=False),
    sa.Column('finish', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('aprove', sa.Boolean(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.Column('reminders_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['events_id'], ['Events.id'], ),
    sa.ForeignKeyConstraint(['reminders_id'], ['Reminders.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['Tags.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users_Events')
    op.drop_table('Tags')
    op.drop_table('Reminders')
    op.drop_table('Events')
    # ### end Alembic commands ###
